### ISSUE TITLE
把我逗乐了

### ISSUE THREAD

**Issue by wwhai** [saysky/SENS#13]
企业级博客，真把我逗乐了。搞个 企业级 helloworld 可还行

**Comment by laipeiyan** [comment]
你好 请问你是谁？我这边没明白你说什么。给我发了好几次了。是不是发错信息了

**Comment by wwhai** [comment]
> 你好 请问你是谁？我这边没明白你说什么。给我发了好几次了。是不是发错信息了

说我吗？串台了还是
