### ISSUE TITLE
关于开源

### ISSUE THREAD

**Issue by homlex** [saysky/SENS#5]
## 500强前30的大佬还做外快生意吗

# 吃相真的难看奥

**Comment by saysky** [comment]
开源了，然后你拿到闲鱼去卖吗？

**Comment by homlex** [comment]
我从来没干过这种事。
如果PO主是因此才不完全开源 那无可非议。
另外我是吐槽你卖的也太贵了。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"言曌"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月18日(星期六) 下午2:39
收件人:&nbsp;"saysky/SENS"<SENS@noreply.github.com&gt;;
抄送:&nbsp;"阳光宅男"<mashiro-e@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [saysky/SENS] 关于开源 (#5)





 
开源了，然后你拿到闲鱼去卖吗？
